---
- name: Install standard software on Windows
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Install Chocolatey
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install standard software packages
      win_chocolatey:
        name:
          - notepadplusplus
          - 7zip
          - googlechrome
          - firefox
          - adobereader
        state: present