---
- name: Create a local user "test" on Windows
  hosts: all
  gather_facts: yes
  collections:
    - ansible.windows

  tasks:
    - name: Create user "test"
      ansible.windows.win_user:
        name: test
        password: PassWord1234!
        state: present
        password_never_expires: yes
        groups:
          - Users