---
- name: Super simple update and reboot
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Update all packages
      package:
        name: "*"
        state: latest

    - name: Reboot after updates
      reboot: